spring:
  graphql:
    graphiql:
      query: |-
        query($id: ID!) {
          artifactRepository(id: $id) {
            name
            url
          }
        }
      variables:
        id: 1
      headers:
        x-test: test